"""Write a human-readable Markdown report for a backtest run, saved under runs/."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path


def _pct(x) -> str:
    return f"{x:.2%}" if isinstance(x, (int, float)) else str(x)


def write_backtest_report(
    runs_dir: Path, ticker: str, strategy: str, params: dict, metrics: dict,
    trades: list[dict], run_id: str, start: str, end: str,
) -> Path:
    runs_dir = Path(runs_dir)
    runs_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = runs_dir / f"{ticker.upper()}_{strategy}_{stamp}.md"

    bh = metrics.get("benchmark_buy_hold")
    excess = metrics.get("excess_vs_buy_hold")
    verdict = ("UNDERPERFORMS buy & hold" if isinstance(excess, (int, float)) and excess < 0
               else "beats buy & hold" if isinstance(excess, (int, float)) else "n/a")

    lines = [
        f"# Backtest report — {ticker.upper()} / {strategy}",
        "",
        f"- run_id: `{run_id}`",
        f"- generated: {datetime.now().isoformat(timespec='seconds')}",
        f"- window: {start} → {end}",
        f"- params: {params}",
        "",
        "## Verdict",
        "",
        f"**{verdict}.** Strategy total return {_pct(metrics.get('total_return'))} vs "
        f"buy & hold {_pct(bh)} (excess {_pct(excess)}).",
        "",
        "## Metrics",
        "",
        "| metric | value |",
        "|---|---|",
        f"| trades | {metrics.get('n_trades')} |",
        f"| win rate | {_pct(metrics.get('win_rate'))} |",
        f"| assigned rate | {_pct(metrics.get('assigned_rate'))} |",
        f"| total return | {_pct(metrics.get('total_return'))} |",
        f"| benchmark (buy & hold) | {_pct(bh)} |",
        f"| excess vs buy & hold | {_pct(excess)} |",
        f"| Sharpe (annualized) | {metrics.get('sharpe_annualized')} |",
        f"| max drawdown | {_pct(metrics.get('max_drawdown'))} |",
        f"| worst trade | {_pct(metrics.get('worst_trade'))} |",
        "",
        "## Worst 3 trades",
        "",
    ]
    worst = sorted(trades, key=lambda t: t.get("return", 0))[:3]
    if worst:
        lines += ["| entry | expiry | strike | underlying@expiry | assigned | return |",
                  "|---|---|---|---|---|---|"]
        for t in worst:
            lines.append(
                f"| {t.get('entry')} | {t.get('expiry')} | {t.get('strike')} | "
                f"{t.get('underlying_at_expiry')} | {t.get('assigned')} | {_pct(t.get('return'))} |"
            )
    else:
        lines.append("_(no trades)_")
    lines += ["", "---", "_Generated by OptionPilot. Backtest is historical; not investment advice._"]

    path.write_text("\n".join(lines))
    return path
